# Tensorflow

## Functions

In [ ]:
import tensorflow as tf

### tf.constant()

In [ ]:
vector=tf.constant([5,10,15,20])
print(vector)

tf.Tensor([ 5 10 15 20], shape=(4,), dtype=int32)


### tf.zeros()

In [ ]:
zero_tensor=tf.zeros([2,3])
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### tf.ones()

In [ ]:
ones_tensor=tf.ones([2,6])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(2, 6), dtype=float32)


### tf.random.uniform()

In [ ]:
random_tensor=tf.random.uniform([2,2],minval=0,maxval=10,dtype=tf.int32)
print(random_tensor)

tf.Tensor(
[[8 2]
 [3 7]], shape=(2, 2), dtype=int32)


In [ ]:
tensor=tf.constant([[1,1],[2,2]])
print(tf.shape(tensor))

tf.Tensor([2 2], shape=(2,), dtype=int32)


### Mathematical Operations

In [ ]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.add(a,b)
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.subtract(a,b)
print(c)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [ ]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.multiply(a,b)
print(c)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [ ]:
a=tf.constant([4,6,8])
b=tf.constant([2,3,4])
c=tf.divide(a,b)
print(c)

tf.Tensor([2. 2. 2.], shape=(3,), dtype=float64)


In [ ]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
c=tf.matmul(a,b)
print(c)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### Reshaping and Manipulating Tensors

In [ ]:
tensor=tf.constant([1,2,3,4,5,6])
reshaped_tensor=tf.reshape(tensor,[2,3])
print(reshaped_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
matrix=tf.constant([[1,2,3],[4,5,6]])
transposed=tf.transpose(matrix)
print(transposed)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [ ]:
tensor=tf.constant([[[1],[2],[3]]])
squeezed=tf.squeeze(tensor)
print(squeezed)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
tensor=tf.constant([1,2,3])
expanded=tf.expand_dims(tensor,axis=1)
print(expanded)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


### Aggregate Functions

In [ ]:
tensor=tf.constant([[1,2],[3,4]])
sum_result=tf.reduce_sum(tensor)
print(sum_result)

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
mean_result=tf.reduce_mean(tensor)
print(mean_result)

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
max_result=tf.reduce_max(tensor)
print(max_result)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
min_result=tf.reduce_min(tensor)
print(min_result)

tf.Tensor(1, shape=(), dtype=int32)


### Indexing and slicing tensors

In [ ]:
tensor=tf.constant([1,2,3,4,5,6])
print(tensor[0])
print(tensor[-1])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
tensor=tf.constant([10,20,30,40,50])
print(tensor[1:4])

tf.Tensor([20 30 40], shape=(3,), dtype=int32)


### Broadcasting

In [ ]:
t1=tf.constant([[1,2,3]])
t2=tf.constant([[1],[2],[3]])
result=t1+t2
print(result)

tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


# Keras

In [ ]:
print('TensorFlow:',tf.__version__)
print("Keras:",tf.keras.__version__)

TensorFlow: 2.18.0
Keras: 3.8.0


## Sequential API

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Activation

In [ ]:
model=Sequential()
model.add(Dense(units=64,input_dim=100))
model.add(Activation('relu'))
model.add(Dense(units=10))
model.add(Activation('softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
from keras.layers import Input,Dense,concatenate
from keras.models import Model

In [ ]:
input1=Input(shape=(100,))
input2=Input(shape=(50,))
hidden1=Dense(64,activation='relu')(input1)
hidden2=Dense(32,activation='relu')(input2)
merged=concatenate([hidden1,hidden2])
output=Dense(10,activation='softmax')(merged)
model=Model(inputs=[input1,input2],outputs=output)